services:
    cache_clearer:
        class: 'Symfony\Component\HttpKernel\CacheClearer\ChainCacheClearer'

    kernel_cache_clearer:
        class: 'Gnugat\MicroFrameworkBundle\Service\KernelCacheClearer'
        public: false
        tags:
            - { name: kernel.cache_clearer }

    cache_clear_command:
        class: 'Gnugat\MicroFrameworkBundle\Command\CacheClearCommand'
        arguments:
            - '@cache_clearer'
            - '%kernel.cache_dir%'
        tags:
            - { name: console.command }
