services:
    cache_warmer:
        class: 'Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate'
        calls:
            - [ enableOptionalWarmers, [] ]

    router_cache_warmer:
        class: 'Gnugat\MicroFrameworkBundle\Service\RouterCacheWarmer'
        public: false
        arguments:
            - '@router'
        tags:
            - {name: kernel.cache_warmer }

    cache_warmup_command:
        class: 'Gnugat\MicroFrameworkBundle\Command\CacheWarmupCommand'
        arguments:
            - '@cache_warmer'
            - '%kernel.cache_dir%'
        tags:
            - { name: console.command }
